// <auto-generated />
using System;
using Evaluacion1erProgreso.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Evaluacion1erProgreso.Migrations
{
    [DbContext(typeof(Evaluacion1erProgresoContext))]
    [Migration("20250428192216_PlanDeRecompensas")]
    partial class PlanDeRecompensas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Evaluacion1erProgreso.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PlanDeRecompensasId")
                        .HasColumnType("int");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlanDeRecompensasId");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("Evaluacion1erProgreso.Models.PlanDeRecompensas", b =>
                {
                    b.Property<int>("PlanDeRecompensasId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlanDeRecompensasId"));

                    b.Property<DateOnly>("FechaCreacion")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoDeRecompensa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("puntos")
                        .HasColumnType("int");

                    b.HasKey("PlanDeRecompensasId");

                    b.ToTable("PlanDeRecompensas");
                });

            modelBuilder.Entity("Evaluacion1erProgreso.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaDeCreacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaDeFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaDeInicio")
                        .HasColumnType("date");

                    b.Property<int>("Monto")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("Evaluacion1erProgreso.Models.Cliente", b =>
                {
                    b.HasOne("Evaluacion1erProgreso.Models.PlanDeRecompensas", "PlanDeRecompensas")
                        .WithMany()
                        .HasForeignKey("PlanDeRecompensasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanDeRecompensas");
                });

            modelBuilder.Entity("Evaluacion1erProgreso.Models.Reserva", b =>
                {
                    b.HasOne("Evaluacion1erProgreso.Models.Cliente", "cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("cliente");
                });

            modelBuilder.Entity("Evaluacion1erProgreso.Models.Cliente", b =>
                {
                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
